id: c7464f28daa442eda8ca6132f6b8d436
initial_creation_type: ocr
source_metadata:
  volumes:
    5a077f9c03df437bbf359eaab24828c5:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ''
      total_pages: 1349
      volume_number: 41
